### ISSUE TITLE
JavaScript error in entry edit screen

### ISSUE THREAD

**Issue by rrelmy** [dannyuk1982/statamic-Duplicate#7]
The script is also executed on the edit screen of an entry and finds dropdowns on the save and preview button but fails with an error.

```
Uncaught TypeError: Cannot read property 'trim' of undefined
    at HTMLUListElement.<anonymous> (addButtons.min.js:1)
    at Function.each (johnny-deps.js?v=2.5.11:1)
    at rt.fn.init.each (johnny-deps.js?v=2.5.11:1)
    at addButtons.min.js:1
```

**Comment by dannyuk1982** [comment]
Where is that error from? I can't see it in the console (chrome), I am changing the add on so it only runs on the screens needed, but just want to be able to check

**Comment by dannyuk1982** [comment]
Should now be fixed (let me know where the error was though)

**Comment by rrelmy** [comment]
I will test it tomorrow.

You did revert my translation update here :-(
https://github.com/dannyuk1982/statamic-Duplicate/commit/4e979401bbe701a2ae9da4218aa11a43bff922da#diff-ed9564ae8fdbb00aeecbf2215c4128cb

**Comment by dannyuk1982** [comment]
I don't know how that happened, sorry!

Is the correct line `'successPage' => 'Die Seite ":title" wurde dupliziert',`?

**Comment by dannyuk1982** [comment]
Should be fixed again now!

**Comment by rrelmy** [comment]
Thanks

The JS error is gone 👍
